version: '3'

services:
    web:
        image: tomcat:9.0.37-jdk11-openjdk-slim
        ports:
            -   9100:8080
        environment: 
            DATABASE_NAME:  spring
            DATABASE_USER:  spring
            DATABASE_PASS:  spring
            DATABASE_URL:   jdbc:mysql://db:3306/spring    
#       volumes: 
#           -   ./build/libs/demo.war:/usr/local/tomcat/webapps/ROOT.war
    
    db:
        image: mongo:4.2.7
        ports: 
            -   27017:27017
        volumes: 
            -   /data/db
        environment: 
            MONGO_INITDB_DATABASE: demo
            MONGO_INITDB_ROOT_USERNAME: demo
            MONGO_INITDB_ROOT_PASSWORD: demo
            
    express:
        build: ./express
        ports:
            -   9101:8081
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: demo
            ME_CONFIG_MONGODB_ADMINPASSWORD: demo
            ME_CONFIG_MONGODB_SERVER: db