
spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    
  messages:
    basename: "i18n/messages"
    cache-duration: -1
    encoding: UTF-8

# env setting
# spring.data.mongodb.uri
# spring.data.mongodb.username
# spring.data.mongodb.password

logging:  level:
    root: OFF    com.example: DEBUG
    org.springframework: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG