debug: true

spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    
  messages:
    basename: "i18n/messages"
    cache-duration: -1
    encoding: UTF-8

logging:  level:
    root: OFF    com.mongodb: DEBUG
    com.example: DEBUG
    org.springframework: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG